name: 'Close expired issues with label'
description: 'This is an Action that closes issues based on the provided label over expire days'
author: 'YUKI "Piro" Hiroshi'
branding:
  icon: 'archive'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
